// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  aws_project_region: 'eu-west-1',
  aws_cognito_identity_pool_id:
    'eu-west-1:d443d121-34b7-4767-ab33-b45f67d0db1b',
  aws_cognito_region: 'eu-west-1',
  aws_user_pools_id: 'eu-west-1_eFoEQcmcB',
  aws_user_pools_web_client_id: '1sosna8rn0puv2savnbgqp8bvs'
};

export default awsmobile;
